### ISSUE TITLE
After switching the display and hiding of the tray several times, clicking on the tray is unresponsive.

### ISSUE THREAD

**Issue by ayangweb** [Cowjiang/zerotier-toolkit#1]
After switching the display and hiding of the tray several times, clicking on the tray is unresponsive.

**Comment by Cowjiang** [comment]
known issue, pending on fixing

**Comment by Code-Agitator** [comment]
> After switching the display and hiding of the tray several times, clicking on the tray is unresponsive.

This issue seems to have disappeared! I'll close it now, and feel free to reopen it if needed.😊

**Comment by Code-Agitator** [comment]
> After switching the display and hiding of the tray several times, clicking on the tray is unresponsive.

> After switching the display and hiding of the tray several times, clicking on the tray is unresponsive.

This issue seems to have disappeared! I'll close it now, and feel free to reopen it if needed.😊

**Comment by Code-Agitator** [comment]
> After switching the display and hiding of the tray several times, clicking on the tray is unresponsive.


This issue seems to have disappeared! I'll close it now, and feel free to reopen it if needed.😊

**Comment by Code-Agitator** [comment]
> After switching the display and hiding of the tray several times, clicking on the tray is unresponsive.

This issue seems to have disappeared! I'll close it now, and feel free to reopen it if needed.😊
